# The Status Binary Sensor exposes the node state (if it’s connected to via MQTT/native API) for Home Assistant.
# https://esphome.io/components/binary_sensor/status.html
platform: status
name: Status
