- alias: general_anyone_leaves_home
  id: d90a6a6a-9ab9-4fbf-bbaf-e284276afb52
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_home
      to: "off"
      for:
        minutes: 1
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.house
      data:
        option: "Away mode"

    - service: notify.stefan
      data:
        title: Vertrek van huis
        message: "Er is niemand thuis. Ik heb alles uit gezet voor je."
        data:
          tag: leaving_alert
          icon: mdi:home-export-outline
