# Setup wifi configuration
# https://esphome.io/components/wifi.html
wifi:
  ssid        : !secret wifi_ssid
  password    : !secret wifi_password
  ap:
    ssid      : "${devicename} Hotspot"
  manual_ip:
    static_ip : ${ip_address}
    gateway   : !secret gateway_ip
    subnet    : 255.255.255.0

# Enable WiFi hotspot
# https://esphome.io/components/captive_portal.html
captive_portal:

# Enable logging
# https://esphome.io/components/logger.html
logger:

# Enable Home Assistant API
# https://esphome.io/components/api.html
api:

# Enable OTA (Over The Air) update component
# https://esphome.io/components/ota.html
ota:
  password    : !secret ota_password
  
# Enable Web server
# https://esphome.io/components/web_server.html
web_server:
  port        : 80

# Setup real time clock time source. Sync with Home Assistant
# https://esphome.io/components/time.html
time:
  - platform  : homeassistant
    id        : homeassistant_time
