# Device: Shelly 1, with detached output
# Info: https://www.esphome-devices.com/devices/shelly-1/
#
# Output is either constantly high (connected to a Hue bulb), or not connected at all.
#
# GPIO Pinout
# Pin     Function
# GPIO4   Relay
# GPIO5   Switch input

esphome:
  name        : $devicename
  platform    : ESP8266
  board       : esp01_1m
  on_boot:
    priority  : -10
    then:
      - if:
          condition:
            # Should return either true or false
            lambda: 'return id(use_output);'
          then:
            - switch.turn_on: switch_output

<<: !include common.yaml

text_sensor:  
  - !include text_sensors/version.yaml

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

binary_sensor:
  - platform             : gpio
    pin                  : GPIO5
    name                 : "${devicelocation} Switch"
    internal             : true                         # Do not expose switch to HA. Send events instead.
    filters:
      - delayed_on       : 10ms
      - delayed_off      : 10ms
    on_state:
      then:
        - if:
            condition: 
              and: 
                - wifi.connected:
                - api.connected:
            then: 
              - homeassistant.event:
                  event  : esphome.button_switched
                  data:
                    name     : $devicename
                    location : $devicelocation
            else: 
              - switch.toggle: switch_output


  - !include binary_sensors/status.yaml

switch:
  - platform             : output
    name                 : "${devicelocation} Light Power"
    output               : 'relay_output'
    id                   : switch_output

  - !include switches/restart.yaml

output:
  - platform             : gpio
    pin                  : GPIO4
    id                   : relay_output
