# Device: Shelly 1
# Info: https://www.esphome-devices.com/devices/shelly-1/
#
# Output toggles when the switch is operated
#
# GPIO Pinout
# Pin     Function
# GPIO4   Relay
# GPIO5   Switch input

esphome:
  name        : $devicename
  platform    : ESP8266
  board       : esp01_1m

<<: !include common.yaml

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/uptime_timestamp.yaml
  - !include sensors/wifi_signal.yaml

binary_sensor:
  - platform             : gpio
    pin                  : GPIO5
    name                 : "${devicelocation} Switch"
    internal             : true                         # Do not expose switch to HA. Send events instead.
    filters:
      - delayed_on       : 10ms
      - delayed_off      : 10ms
    on_state:
      then:
        - light.toggle   : light_output
        - homeassistant.event:
            event        : esphome.button_switched
            data:
              name       : $devicename
              location   : $devicelocation

  - !include binary_sensors/status.yaml

light:
  - platform             : binary
    name                 : "${devicelocation} Light"
    output               : relay_output
    id                   : light_output
    restore_mode         : restore_default_off

switch:
  - !include switches/restart.yaml

output:
  - platform             : gpio
    pin                  : GPIO4
    id                   : relay_output
  