- alias: outside_christmas_lights
  id: 9c93a7e9-ea9d-401a-b88f-2ceef305f743
  mode: queued
  trigger:
    - platform: homeassistant
      event: start # in case the states aren't properly restored
      id: ha_start
    - platform: event
      event_type: automation_reloaded # in case automations reload
    - platform: state
      entity_id: input_boolean.christmas_time
    - platform: time
      at:
        - &turn_lights_on "07:30:00" # Turn on lights in the morning
        - &turn_lights_off "23:30:00" # Turn off lights at night
    - platform: sun # Turn off lights some time after sunrise
      event: sunrise
      offset: &sunrise_offset "00:30:00"
    - platform: sun # Turn on lights some time before sunset
      event: sunset
      offset: &sunset_offset "-00:30:00"

  variables:
    entities:
      - light.inside # christmas light string in front kitchen window
      - light.outside # christmas light string in garden trees
      - light.christmaslights_in_front # light in 2 trees in front of house

  action:
    - alias: Check if this is triggered by HA restart
      if:
        condition: trigger
        id: ha_start
      then:
        delay: "00:01:00" # Zigbee plug needs time to connect after HA start

    - if:
        - alias: Check if lights need to turn off
          or:
            - alias: Xmas has come and gone! :(
              condition: state
              entity_id: input_boolean.christmas_time
              state: "off"
            - alias: Too damn early (or late actually)
              condition: time
              after: *turn_lights_off
              before: *turn_lights_on
            - alias: Turn off during daytime
              condition: sun
              after: sunrise
              after_offset: *sunrise_offset
              before: sunset
              before_offset: *sunset_offset
      then:
        - alias: "Turning lights off"
          service: light.turn_off
          target:
            entity_id: "{{ entities }}"
      else:
        - alias: "Turning lights on"
          service: light.turn_on
          target:
            entity_id: "{{ entities }}"
