- id: '1656270214832'
  alias: bedroom_3_turn_on
  description: ''
  trigger:
  - device_id: c4fdaf721bba5603ad4ea2dd93e0e086
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      area_id: slaapkamer_3
  mode: single
- id: '1656270271960'
  alias: bedroom_3_turn_off
  description: ''
  trigger:
  - device_id: c4fdaf721bba5603ad4ea2dd93e0e086
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: slaapkamer_3
  mode: single
- id: '1659557754551'
  alias: Notify tv doorbell
  description: Show notification on tv when doorbell rings
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.deurbel_ringing_sensor
    from: 'False'
    to: 'True'
  condition:
  - condition: device
    type: is_on
    device_id: 66a5203e31dc467686b8cda0d649733b
    entity_id: switch.roelofs_harmony_hub_tv_kijken
    domain: switch
  action:
  - service: notify.android_tv
    data:
      title: Deurbel gaat!
      message: Er staat iemand voor de deur.
  mode: single
