- id: '1615364843996'
  alias: Wake-up light alarm with sunrise effect
  description: ''
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      manual_time: '7:00:00'
      light_entity: light.bedroom_master_ceiling
      timestamp_sensor: sensor.stefan_phone_app_next_alarm
      check_entity: binary_sensor.workday_sensor
