# The wifi_info text sensor platform exposes different WiFi information via text sensors.
# https://esphome.io/components/text_sensor/wifi_info.html
platform  : wifi_info
ip_address:
  name    : "${devicelocation} IP Address"
ssid:
  name    : "${devicelocation} Connected SSID"
bssid:
  name    : "${devicelocation} Connected BSSID"
