# The wifi_info text sensor platform exposes different WiFi information via text sensors.
# https://esphome.io/components/text_sensor/wifi_info.html
platform: wifi_info
ip_address:
  name: IP Address
ssid:
  name: SSID
bssid:
  name: BSSID
