- alias: bathroom_auto_lights
  id: db7f7aef-5ebd-4afc-8ebc-2c225e50bdcd
  trigger:
    - platform: time
      at: "22:55:11"
  condition:
    - condition: state
      entity_id: "binary_sensor.anybody_home"
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.bathroom_ceiling
    - delay: "00:14:51"
    - service: light.turn_off
      entity_id: light.bathroom_ceiling
