- alias: bathroom_climate
  id: 818bccea-3335-4f3d-b62b-4490c4f9ea03
  mode: queued

  trigger:
    - platform: homeassistant
      event: start # in case the states aren't properly restored
      id: ha_start

    - platform: event
      event_type: automation_reloaded

    - platform: state
      entity_id:
        - binary_sensor.bathroom_windowsensor
        - binary_sensor.anybody_home
        - binary_sensor.bathroom_hygrostat
        - input_select.house

    - platform: time
      at:
        - &weekday_morning_start "06:30:00"
        - &weekday_morning_end "07:30:00"
        #        - &weekend_morning_start "07:30:00"
        #        - &weekend_morning_end "08:30:00"
        - &evening_start "18:45:00"
        - &evening_end "20:30:00"

  variables:
    anchors:
      - &target
        target:
          area_id: badkamer

      - &turn_off
        <<: *target
        alias: "Turn off heating"
        service: climate.set_hvac_mode
        data:
          hvac_mode: "off"

      - &turn_on
        <<: *target
        alias: "Turn on heating"
        service: climate.set_hvac_mode
        data:
          hvac_mode: "heat"

      - &turn_down
        <<: *target
        alias: "Turn down heating"
        service: climate.set_temperature
        data:
          temperature: 15.0

      - &turn_up
        <<: *target
        alias: "Turn up heating"
        service: climate.set_temperature
        data:
          temperature: 26.0

  action:
    - alias: Check if this is triggered by HA restart
      choose:
        - conditions:
            condition: trigger
            id: ha_start
          sequence:
            - delay:
                minutes: 2

    - choose:
        - conditions:
            - alias: "When nobody is home"
              condition: state
              entity_id: binary_sensor.anybody_home
              state: "off"
          sequence:
            - *turn_off

        - conditions:
            - alias: "When outside temperature is too high"
              condition: numeric_state
              entity_id: sensor.buienradar_temperature
              above: 18.0
          sequence:
            - *turn_off

        - conditions:
            - alias: "When the window is open"
              condition: state
              entity_id: binary_sensor.bathroom_windowsensor
              state: "on"
          sequence:
            - *turn_off

        - conditions:
            - alias: "When we are sleeping"
              condition: state
              entity_id: input_select.house
              state: "Sleep mode"
          sequence:
            - *turn_off

        - conditions:
            - alias: "When someone is in the shower"
              condition: state
              entity_id: binary_sensor.bathroom_hygrostat
              state: "on" # high humidity detected
          sequence:
            - *turn_on
            - *turn_up

        - alias: "When it is morning on a weekday"
          conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on" # it is a weekday
            - condition: time
              after: *weekday_morning_start
              before: *weekday_morning_end
          sequence:
            - *turn_on
            - *turn_up

        #        - alias: "When it is morning in the weekend"
        #          conditions:
        #            - condition: state
        #              entity_id: binary_sensor.workday_sensor
        #              state: "off" # it is weekend
        #            - condition: time
        #              after: *weekend_morning_start
        #              before: *weekend_morning_end
        #          sequence:
        #            - *turn_on
        #            - *turn_up

        - conditions:
            - alias: "When it is evening"
              condition: time # Set temp on evenings
              after: *evening_start
              before: *evening_end
          sequence:
            - *turn_on
            - *turn_up

      alias: Set low temperature
      default:
        - *turn_on
        - *turn_down
# Credits: https://github.com/frenck/home-assistant-config/blob/master/automations/bedroom_flynn/climate.yaml
