- alias: bathroom_lights_cleaning_mode
  id: fcdac39a-9635-43cc-a8af-6ea5f3965db6
  trigger:
    - platform: state
      entity_id: input_select.house
      to: "Cleaning mode"
  action:
    - service: light.turn_on
      target:
        area_id: badkamer
      data:
        color_temp: 180
        brightness: 255
        transition: 1
