- alias: general_house_mode_away_enable
  id: d90a6a6a-9ab9-4fbf-bbaf-e284276afb52

  trigger:
    - platform: numeric_state
      entity_id: zone.home
      below: 1
      for:
        seconds: 30

  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.house
          state: "Guest mode"

  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.house
      data:
        option: "Away mode"

    - service: notify.stefan
      data:
        title: Vertrek van huis
        message: "Er is niemand thuis. Ik heb alles uit gezet voor je."
        data:
          tag: leaving_alert
          icon: mdi:home-export-outline
