- alias: bedroom_master_6_gang_remote
  id: 0a2927be-2460-4caf-8adc-4a92667bfe8a
  mode: queued
  max: 3
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: d16caab4c9f94f688fb24f14203fe04c
  action:
    - variables:
        command: "{{ trigger.event.data.command }}"
        cluster_id: "{{ trigger.event.data.cluster_id }}"
        endpoint_id: "{{ trigger.event.data.endpoint_id }}"
        args: "{{ trigger.event.data.args }}"
        cur_brightness: "{{ state_attr('light.bedroom_master_ceiling', 'brightness') }}"
    - choose:
        # TOP LEFT
        - conditions:
            - "{{ cluster_id == 18 }}"
            - "{{ endpoint_id == 1 }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.bedroom_master_ceiling
              data:
                transition: 1

        # TOP RIGHT
        - conditions:
            - "{{ cluster_id == 18 }}"
            - "{{ endpoint_id == 2 }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.bedroom_master_ceiling
              data:
                transition: 1
        #              profile       : relax

        # MID LEFT
        - conditions:
            - "{{ cluster_id == 18 }}"
            - "{{ endpoint_id == 3 }}"
          sequence:
            - choose:
                - conditions: "{{ (cur_brightness - 25) >= 1 }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.bedroom_master_ceiling
                      data:
                        transition: 1
                        brightness_step: -25
              default:
                - service: light.turn_on
                  target:
                    entity_id: light.bedroom_master_ceiling
                  data:
                    transition: 1
                    brightness: 1

        # MID RIGHT
        - conditions:
            - "{{ cluster_id == 18 }}"
            - "{{ endpoint_id == 4 }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.bedroom_master_ceiling
              data:
                transition: 1
                brightness_step: 25

        # BOTTOM LEFT / RIGHT
        - conditions:
            - "{{ cluster_id == 18 }}"
            - condition: or
              conditions:
                - "{{ endpoint_id == 5 }}"
                - "{{ endpoint_id == 6 }}"
          sequence:
            - service: input_select.select_option
              target:
                entity_id: input_select.house
              data:
                option: "Sleep mode"
#
# Complete zha_event Data contents:
# "device_ieee": "04:cf:8c:df:3c:75:b3:fb",
# "unique_id": "04:cf:8c:df:3c:75:b3:fb:1:0x0012",
# "device_id": "d16caab4c9f94f688fb24f14203fe04c",
# "endpoint_id": 1,
# "cluster_id": 18,
# "command": "1_single",
# "args": {
#     "button": 1,
#     "press_type": "single",
#     "attr_id": 85,
#     "value": 1
# }
