- alias: bedroom_master_auto_lights
  id: 7635cff0-cb1d-409e-9c2d-df9d4a5b0348
  trigger:
    - platform: time
      at: "23:04:42"
  condition:
    - condition: state
      entity_id: "binary_sensor.anybody_home"
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.bedroom_master_ceiling
    - delay: "00:25:21"
    - service: light.turn_off
      entity_id: light.bedroom_master_ceiling
