# Setup wifi configuration
# https://esphome.io/components/wifi.html
wifi:
  id: component_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${slug} Hotspot"
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret gateway_ip
    subnet: 255.255.255.0
    dns1: !secret ip_address_adguardhome

#  use_address: nodemcu_office.local

# Enable WiFi hotspot
# https://esphome.io/components/captive_portal.html
captive_portal:

# Enable logging
# https://esphome.io/components/logger.html
logger:
  id: component_logger

# Enable Home Assistant API
# https://esphome.io/components/api.html
api:
  id: component_api
  encryption:
    key: ${api_encryption_key}

# Enable OTA (Over The Air) update component
# https://esphome.io/components/ota.html
ota:
  id: component_ota
  password: !secret ota_password

# Enable Web server
# https://esphome.io/components/web_server.html
web_server:
  id: component_web_server
  port: 80

# Setup real time clock time source. Sync with Home Assistant
# https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Amsterdam"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

  - platform: sntp
    id: sntp_time
    timezone: "Europe/Amsterdam"

text_sensor:
  - <<: !include text_sensors/version.yaml
  - <<: !include text_sensors/wifi_info.yaml

sensor:
  - <<: !include sensors/uptime.yaml
  - <<: !include sensors/uptime_timestamp.yaml
  - <<: !include sensors/wifi_signal_percentage.yaml
  - <<: !include sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

binary_sensor:
  - <<: !include binary_sensors/status.yaml

button:
  - <<: !include buttons/restart.yaml
