- alias: living_room_christmas_tree
  id: 8814ae24-d5e9-431c-b9cb-7fe7c66cf607
  mode: queued
  trigger:
    - platform: homeassistant
      event: start # in case the states aren't properly restored
      id: ha_start
    - platform: event
      event_type: automation_reloaded # in case automations reload
    - platform: state
      entity_id: input_boolean.christmas_time
      id: christmas_time_trigger
    - platform: time
      at:
        - &turn_lights_on "07:30:00" # Turn on lights in the morning
        - &turn_lights_off "23:30:00" # Turn off lights at night
    - platform: state
      entity_id:
        - input_select.house
        - binary_sensor.anybody_home

  action:
    - alias: Stop automation when it is not christmas time, and christmas time input boolean not triggered this
      if:
        - alias: Only operate switch during christmas time
          condition: state
          entity_id: input_boolean.christmas_time
          state: "off"
        - not:
          - alias: Input boolean switched on or off
            condition: trigger
            id: christmas_time_trigger
      then:
        stop: "Stop running the rest of the sequence, it's not christmas yet!"

    - alias: Check if this is triggered by HA restart
      if:
        condition: trigger
        id: ha_start
      then:
        delay: "00:01:00" # Zigbee plug needs time to connect after HA start

    - if:
        - alias: Check if lights need to turn off
          or:
            - alias: Xmas has come and gone! :(
              condition: state
              entity_id: input_boolean.christmas_time
              state: "off"
            - alias: Gone fishing.. (need to delete this sensor)
              condition: state
              entity_id: binary_sensor.anybody_home
              state: "off"
            - alias: Sleepy time
              condition: state
              entity_id: input_select.house
              state: "Sleep mode"
            - alias: Also gone fishing..
              condition: state
              entity_id: input_select.house
              state: "Away mode"
            - alias: Too damn early (or late actually)
              condition: time
              after: *turn_lights_off
              before: *turn_lights_on
      then:
        - alias: "Turning tree off"
          service: switch.turn_off
          target:
            entity_id: switch.living_room_charging_station_outlet
      else:
        - alias: "Turning tree on"
          service: switch.turn_on
          target:
            entity_id: switch.living_room_charging_station_outlet
