#################################################################
## Start activity TV kijken when Marcella is home at 20:00h
#################################################################
- alias: living_room_harmony_start_activity_gtst
  id: 9e6f9c28-6ade-492f-8346-3bccb57b1b27
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: state
      entity_id: person.marcella
      state: "home"
    - condition: state
      entity_id: "binary_sensor.workday_sensor"
      state: "on"
    - condition: state
      entity_id: remote.roelofs_harmony_hub
      state: "off"
  action:
    - service: remote.turn_on
      entity_id: remote.roelofs_harmony_hub
      data:
        activity: "Tv kijken"
    - delay: "00:00:10"
    - service: remote.send_command # The Power input on the remote is a toggle, so you never know if you turn it off or on.
      data:
        entity_id: remote.roelofs_harmony_hub
        device: "Youfone"
        command:
          - "A" # The 'A' input always turns the device on.
    - delay: "00:00:14" # Wait for Youfone AVR to boot
    - service: remote.send_command
      data:
        entity_id: remote.roelofs_harmony_hub
        device: "Youfone"
        command:
          - "4" # Set correct channel
