#################################################################
## Switch lights when darkness falls
#################################################################
- alias: living_room_sunset_lights_on
  id: 6a4d749f-c854-4e68-9b58-c031fa06cd13
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 3.0 # Can be a positive or negative number

  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.living_room_lights
          - light.dining_area_ceiling
      data:
        transition: 30

    - alias: "If nobody is home"
      if: "{{ states('zone.home') | int(0) == 0 }}"
      then:
        - alias: "Wait for anyone to come home"
          wait_template: "{{ states('zone.home') | int(0) > 0 }}"
          timeout: "01:38:11"
        - if: "{{ not wait.completed }}"
          then:
            - alias: "Nobody came home, turn off the lights again"
              service: light.turn_off
              target:
                entity_id:
                  - light.living_room_lights
                  - light.dining_area_ceiling
