- alias: living_room_switch_charging_station_outlet
  id: ec286a80-c1f2-409c-8f14-190b43a2adf0
  mode: single
  trigger:
    - platform: state
      entity_id: switch.living_room_entertainment_outlet

  condition:
    - alias: During christmas time this plug switches the christmas tree
      condition: state
      entity_id: input_boolean.christmas_time
      state: "off"

  action:
    - alias: Folow the state of another smart plug
      if:
        condition: state
        entity_id: switch.living_room_entertainment_outlet
        state: "on"
      then:
        service: switch.turn_on
        target:
          entity_id: switch.living_room_charging_station_outlet
      else:
        service: switch.turn_off
        target:
          entity_id: switch.living_room_charging_station_outlet
