- alias: living_room_switch_entertainment_outlet_on
  id: ff13448c-e65c-497a-8817-42d4eec92607
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.house
      from: "Sleep mode"
    - platform: state
      entity_id: binary_sensor.anybody_home
      from: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.living_room_entertainment_outlet
    - wait_for_trigger: # Wait for android set-top box to start up
        - platform: state
          entity_id: media_player.android_tv_192_168_1_21
          to: "idle"
          for: "00:00:10"
      timeout: "00:05:00"
      continue_on_timeout: false
    - service: media_player.turn_off
      target:
        entity_id: media_player.android_tv_192_168_1_21
