# Controlling my Buva Qstream ventilation system using:
# * A Wemos D1 mini lite (an ESP8266 based board)
# * A Wemos power shield so I can power the Wemos from the ventilation units 12V supply.
# * A simple PWM to 10V convertor like this: https://www.cheaptech.nl/pwm-signaal-te-voltage-converter-1-3-khz-0-10-v-pw.html
# * The amazing ESPHome firmware tool: https://esphome.io
# * Home Assistant to tie it all together: https://www.home-assistant.io

# I/O List
#
# OUTPUTS:
#   GPIO4   D2    pwm_output      PWM pulse output to the 10V converter
#   GPIO2   D4                    Status Led              connected to on-board LED, pin is high at BOOT, boot failure if pulled LOW
#
# Don't use pin D3 (GPIO0) as output! The D1 won't boot because it is pulled low.

# Reference / photo: https://www.wemos.cc/en/latest/d1/d1_mini.html
# Credits: https://gist.github.com/SqyD/38d10391c2e21988406d2bdaec24f031

substitutions:
  slug: "d1-mini-mech-vent"
  name: "Mech Vent"
  description: "D1 Mini in mechanical ventilation box"
  ip_address: !secret d1_mini_MV_ip_address
  api_encryption_key: !secret d1_mini_MV_api_encryption_key

esphome:
  name: "${slug}"
  comment: "${description}"
  build_path: "./.build/${slug}/"
  platform: ESP8266
  board: d1_mini_lite

packages:
  common: !include common/common.yaml

output:
  platform: esp8266_pwm
  pin: D2
  frequency: 2000 Hz
  id: pwm_output

# Voorgeprogrammeerde capaciteit (uit usermanual):
#  - Hoogstand (L4)   : 70 % - 7 V aansturing
#  - Hoogstand (L3)   : 50 % - 5 V aansturing
#  - Middenstand (L2) : 30 % - 3 V aansturing
#  - Laagstand (L1)   : 20 % - 2 V aansturing
#  - Nachtstand (N) = Hoogstand (L3)

fan:
  platform: speed
  id: fancomponent
  name: "${name} Fan"
  output: pwm_output
  speed_count: 100 # %

# Configuring individual speeds is deprecated.
#  speed:
#    low             : 0.25
#    medium          : 0.45
#    high            : 0.8

# https://esphome.io/components/status_led.html
status_led:
  pin:
    number   : GPIO2
    inverted : true
