substitutions:
  devicename     : "esp32cam_1"
  devicelocation : "ESP32Cam 1"
  ip_address     : !secret ip_address_esp32cam1
  status_led_pin : GPIO33  # Red led output

esphome:
  name           : $devicename
  platform       : ESP32
  board          : esp32dev
# board          : esp-wrover-kit  # alternative board

<<: !include shared/common.yaml
<<: !include shared/status_led.yaml

binary_sensor:
  - !include shared/binary_sensors/status.yaml

sensor:
  - !include shared/sensors/uptime.yaml
  - !include shared/sensors/uptime_timestamp.yaml
  - !include shared/sensors/wifi_signal.yaml

switch:
  - !include shared/switches/restart.yaml
  # Flash light of camera
  - platform        : gpio
    pin             : GPIO4
    name            : "${devicelocation} Flash"

# https://esphome.io/components/esp32_camera.html
esp32_camera:
  external_clock:
    pin             : GPIO0
    frequency       : 20MHz
  i2c_pins:
    sda             : GPIO26
    scl             : GPIO27
  data_pins         : [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin         : GPIO25
  href_pin          : GPIO23
  pixel_clock_pin   : GPIO22
  power_down_pin    : GPIO32

  # Image settings
  name              : Image
