# DEVICE:
# ESP32S ESP-WROOM-32
# https://www.aliexpress.com/item/1005002952149285.html
# ESP32 30Pin
# Drivers for built-in 2102 chip:
# https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers
#
# I/O List (left side of device)
#
# EN    Enable                  Connected to Restart button on ESP32.
# VP    GPIO 36   Input only    I could not use these inputs. No pull up/down resistors, so input is floating when not connected.
# VN    GPIO 39   Input only    This input is somehow bridged with GPIO 36? Both inputs switch at the same time.
# D34   GPIO 34   Input only    I could not use these inputs. No pull up/down resistors, so input is floating when not connected.
# D35   GPIO 35   Input only    I could not use these inputs. No pull up/down resistors, so input is floating when not connected.
# D32   GPIO 32   Ok            relay1_output
# D33   GPIO 33   Ok            relay2_output
# D25   GPIO 25   Ok            relay3_output
# D26   GPIO 26   Ok            relay4_output
# D27   GPIO 27   Ok            relay5_output
# D14   GPIO 14   outputs PWM signal at boot
# D12   GPIO 12   Output only; boot fail if pulled high
# D13   GPIO 13   Ok            relay6_output
# GND   Ground
# VIN   5V DC
#
# I/O List (right side of device)
#
# D18   GPIO 18   Ok            Switch Bedroom
# D17   GPIO 17   Ok            Switch Laundry room
# D16   GPIO 16   Ok            Switch Office
#
# GPIO 2 is connected to blue on-board LED
#
# Pinout (30Pin board): https://www.studiopieters.nl/esp32-pinout/
# Reference:            https://randomnerdtutorials.com/esp32-pinout-reference-gpios/
#
# Note: When all 3 light switches are in the down position, all the inputs are low.

substitutions:
  slug: "nodemcu-office"
  name: "Home Office"
  description: "ESP32 - Lightcontrol for attic"
  ip_address: !secret ip_address_nodemcu_1

esphome:
  name: "${slug}"
  comment: "${description}"
  build_path: "./.build/${slug}/"
  platform: ESP32
  board: nodemcu-32s
  on_boot:
    priority: -10
    then:
      - switch.turn_on: switch_relay4
      - switch.turn_on: switch_relay6

packages:
  common: !include common/common.yaml

output:
  - platform: gpio
    id: relay1_output
    pin: GPIO32
    inverted: true
  - platform: gpio
    id: relay2_output
    pin: GPIO33
    inverted: true
  - platform: gpio
    id: relay3_output
    pin: GPIO25
    inverted: true
  - platform: gpio
    id: relay4_output
    pin: GPIO26
    inverted: true
  - platform: gpio
    id: relay5_output
    pin: GPIO27
    inverted: true
  - platform: gpio
    id: relay6_output
    pin: GPIO13
    inverted: true

light:
  - platform: binary
    id: lightstudy1
    name: "${name} 1"
    output: relay1_output
  - platform: binary
    id: lightstudy2
    name: "${name} 2"
    output: relay2_output
  - platform: binary
    id: lightstudy3
    name: "${name} 3"
    output: relay3_output
#  - platform        : binary   # Changed this for a smart Ikea bulb.
#    id              : lightbedroom
#    name            : "Bedroom 3 Ceiling"
#    output          : relay4_output
  - platform: binary
    id: lightlaundry
    name: "Laundry room Ceiling"
    output: relay5_output

switch:
  - platform: output
    name: "Bedroom 3 Ceiling Power"
    output: relay4_output
    id: switch_relay4
  - platform: output
    name: "Second Floor Landing Ceiling Power"
    output: relay6_output
    id: switch_relay6

binary_sensor:
  # Bedroom switch
  - platform: gpio
    name: "Bedroom 3 Switch"
    internal: true # Do not expose switch to HA. Send events instead.
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 20ms
    on_state:
      then:
#        - light.toggle: lightbedroom
        - homeassistant.event:
            event: esphome.button_switched
            data:
              name: "${slug}"
              location: "Bedroom 3"

  # Laundry room switch
  - platform: gpio
    name: "Laundry room Switch"
    internal: true # Do not expose switch to HA. Send events instead.
    pin:
      number: GPIO17
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 20ms
    on_state:
      then:
        - light.toggle: lightlaundry
        - homeassistant.event:
            event: esphome.button_switched
            data:
              name: "${slug}"
              location: "Laundry room"

  # Office switch
  - platform: gpio
    name: "${name} Switch"
    internal: true # Do not expose switch to HA. Send events instead.
    pin:
      number: GPIO16
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 20ms
    on_state:
      then:
        - if:
            condition:
              or:
                - light.is_on: lightstudy1
                - light.is_on: lightstudy2
                - light.is_on: lightstudy3
            then:
              - light.turn_off: lightstudy3
              - delay: 300ms
              - light.turn_off: lightstudy2
              - delay: 300ms
              - light.turn_off: lightstudy1
            else:
              - light.turn_on: lightstudy1
              - delay: 300ms
              - light.turn_on: lightstudy2
              - delay: 300ms
              - light.turn_on: lightstudy3
        - homeassistant.event:
            event: esphome.button_switched
            data:
              name: "${slug}"
              location: "${name}"

# https://esphome.io/components/status_led.html
status_led:
  pin:
    number: GPIO2
    inverted: false
