# I/O List
#
# OUTPUTS:
#   GPIO4   D2    relay1_output   Home office 1
#   GPIO5   D1    relay2_output   Home office 2
#   GPIO12  D6    relay3_output   Home office 3
#   GPIO13  D7    relay4_output   Bedroom
#   GPIO14  D5    relay5_output   Laundry room
#   GPIO15  D8    relay6_output   Landing (power toggle)  Boot fails if pulled HIGH
#   GPIO2   D4                    Status Led              connected to on-board LED, pin is high at BOOT, boot failure if pulled LOW
#
# INPUTS:
#   GPIO0   D3                    Switch Bedroom          boot failure if pulled LOW
#   GPIO1   TX                    Switch Laundry room     pin is high at BOOT, boot failure if pulled LOW
#   GPIO3   RX                    Switch Office           pin is high at BOOT
#
# LET OP!!!!!!!! ALLE 3 DE SCHAKELAARS MOETEN NAAR BENEDEN STAAN! DAN ZIJN DE 3 INPUTS LAAG.
#
# Reference / photo: https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

substitutions:
  slug: "nodemcu-office"
  name: "Home Office"
  description: "Broken as fuck!!"
  ip_address: !secret ip_address_nodemcu_1

esphome:
  name: "${slug}"
  comment: "${description}"
  build_path: "./.build/${slug}/"
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    priority: -10
    then:
      - switch.turn_on: switch_relay4
#      - switch.turn_on: switch_relay6

packages:
  common: !include common/common.yaml

output:
  - platform: gpio
    id: relay1_output
    pin: GPIO4
    inverted: true
  - platform: gpio
    id: relay2_output
    pin: GPIO5
    inverted: true
  - platform: gpio
    id: relay3_output
    pin: GPIO12
    inverted: true
  - platform: gpio
    id: relay4_output
    pin: GPIO13
    inverted: true
  - platform: gpio
    id: relay5_output
    pin: GPIO14
    inverted: true
  - platform: gpio
    id: relay6_output
    pin: GPIO15
    inverted: true

light:
  - platform: binary
    id: lightstudy1
    name: "${name} 1"
    output: relay1_output
  - platform: binary
    id: lightstudy2
    name: "${name} 2"
    output: relay2_output
  - platform: binary
    id: lightstudy3
    name: "${name} 3"
    output: relay3_output
  #  - platform        : binary   # Changed this for a smart Ikea bulb.
  #    id              : lightbedroom
  #    name            : "Bedroom 3 Ceiling"
  #    output          : relay4_output
  - platform: binary
    id: lightlaundry
    name: "Laundry room Ceiling"
    output: relay5_output

switch:
  - platform: output
    name: "Bedroom 3 Ceiling Power"
    output: relay4_output
    id: switch_relay4

# Update 2021-05-24: This output was connected to GPIO15 D8.
# But the esp would fail to boot up.
# When I disconnected this output, it would boot up fine.
# So this output must be pulled high on bootup, somehow....
# I disconnected the output, and connected the relay to GND. This switches the relay permanently.
#  - platform        : output
#    name            : "Second Floor Landing Ceiling Power"
#    output          : relay6_output
#    id              : switch_relay6

binary_sensor:
  # Bedroom switch
  # This lightswitch is disabled, there is a big wardrobe in front of it.
  #  - platform   : gpio
  #    name       : "Bedroom 3 Switch"
  #    internal   : true                         # Do not expose switch to HA. Send events instead.
  #    pin:
  #      number   : GPIO0
  #      inverted : True
  #      mode     : INPUT_PULLUP
  #    filters:
  #      - delayed_on_off : 20ms
  #    on_state:
  #      then:
  #        - light.toggle : lightbedroom
  #        - homeassistant.event:
  #            event        : esphome.button_switched
  #            data:
  #              name       : "${slug}"
  #              location   : $name

  # Laundry room switch
  - platform: gpio
    name: "Laundry room Switch"
    internal: true # Do not expose switch to HA. Send events instead.
    pin:
      number: GPIO1
      inverted: True
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 20ms
    on_state:
      then:
        - light.toggle: lightlaundry
        - homeassistant.event:
            event: esphome.button_switched
            data:
              name: "${slug}"
              location: "${name}"

  # Office switch
  - platform: gpio
    name: "${name} Switch"
    internal: true # Do not expose switch to HA. Send events instead.
    pin:
      number: GPIO3
      inverted: True
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 20ms
    on_state:
      then:
        - if:
            condition:
              or:
                - light.is_on: lightstudy1
                - light.is_on: lightstudy2
                - light.is_on: lightstudy3
            then:
              - light.turn_off: lightstudy3
              - delay: 300ms
              - light.turn_off: lightstudy2
              - delay: 300ms
              - light.turn_off: lightstudy1
            else:
              - light.turn_on: lightstudy1
              - delay: 300ms
              - light.turn_on: lightstudy2
              - delay: 300ms
              - light.turn_on: lightstudy3
        - homeassistant.event:
            event: esphome.button_switched
            data:
              name: "${slug}"
              location: "${name}"

# https://esphome.io/components/status_led.html
status_led:
  pin:
    number   : GPIO2
    inverted : true
