substitutions:
  slug: "powerplug-1"
  name: "Staircase Closet Floorheatingpump Outlet"
  description: "Blitzwolf BW-SHP6. Floorheatingpump outlet"
  current_res: "0.00290" # Higher value gives lower watt readout
  voltage_div: "940" # Lower value gives lower voltage readout
  ip_address: !secret powerplug1_ip_address
  api_encryption_key: !secret powerplug1_api_encryption_key
  max_power: "2000" # 2300W for 10A

packages:
  device: !include devices/powerplug.yaml
