substitutions:
  slug: "powerplug-2"
  name: "Living Room Entertainment Outlet"
  description: "Blitzwolf BW-SHP6. Living Room Entertainment outlet"
  current_res: "0.00290" # Higher value gives lower watt readout
  voltage_div: "940" # Lower value gives lower voltage readout
  ip_address: !secret ip_address_powerplug2
  max_power: "2000" # 2300W for 10A

packages:
  device: !include devices/powerplug.yaml
