substitutions:
  slug: "shelly-4"
  name: "First Floor Landing"
  description: "Shelly device behind lightswitch on 1st floor landing. Relay is connected, but not switching."
  ip_address: !secret shelly4_ip_address
  api_encryption_key: !secret shelly4_api_encryption_key

globals:
  - id: use_output
    type: bool
    restore_value: true # output relay should be constantly high.
    initial_value: "true"

packages:
  device: !include devices/shelly_detached_output.yaml
