#################################################################
## Flash light when doorbell is pushed and chime is disabled.
#################################################################
- alias: utility_closet_doorbell_pushed_flash_lights
  id: 41309159-285e-4c61-b47b-134d3945191d
  trigger:
    platform: state
    entity_id: binary_sensor.deurbel_ringing_sensor
    from: "False"
    to: "True"

  condition:
    condition: state
    entity_id: input_select.house
    state:
      - "Normal"
      - "Guest mode"
      - "Cleaning mode"
  action:
    - service: scene.create
      data:
        scene_id: flash_lights_restore_scene
        snapshot_entities:
          - light.first_floor_landing_ceiling
          - light.second_floor_landing_ceiling
          - light.home_office_ceiling

    - service: light.turn_on
      target:
        entity_id:
          - light.first_floor_landing_ceiling
          - light.second_floor_landing_ceiling
          - light.home_office_ceiling
      data:
        brightness: 255
        flash: long

    - delay: "00:00:30"

    - service: scene.turn_on
      target:
        entity_id: scene.flash_lights_restore_scene
