- alias: utility_closet_homebase_alarmmode_set
  id: a44feda6-fd98-45bb-b805-b7a15e111751
  mode: single

  trigger:
    - platform: homeassistant
      event: start # in case the states aren't properly restored
      id: ha_start

    - platform: event
      event_type: automation_reloaded

    - platform: state
      entity_id: input_select.house

  action:
    - alias: Check if this is triggered by HA restart
      if:
        condition: trigger
        id: ha_start
      then:
        delay: "00:01:00" # Zigbee plug needs time to connect after HA start

    - if:
        alias: "House is in Away mode"
        condition: state
        entity_id: input_select.house
        state: "Away mode"
      then:
        alias: "We are away, set to arm_away"
        service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.homebase
        data: {}
      else:
        alias: "We are home, set to arm_home"
        service: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.homebase
        data: {}
