# SHTCx Temperature+Humidity Sensor
# https://esphome.io/components/sensor/shtcx.html

platform: shtcx
temperature:
  id: sensor_temperature
  name: Temperature
humidity:
  id: sensor_humidity
  name: Humidity
update_interval: 600s
