- alias: laundry_room_mechanical_ventilation
  id: 2975023b-791e-480f-a803-064d369830c0
  mode: single
  max_exceeded: silent
  trigger:
    - platform: homeassistant
      event: start
      id: ha_start

    - platform: event
      event_type: automation_reloaded

    - platform: state
      entity_id: input_select.house
      to: "Sleep mode"

    - platform: state
      entity_id: input_select.house
      to: "Sleep mode"
      for: "00:30:00"

    - platform: state
      entity_id: input_select.house
      from: "Sleep mode"

    - platform: state
      entity_id: binary_sensor.anybody_home

    - platform: state
      entity_id: binary_sensor.bathroom_hygrostat
      from: ~

  action:
    - alias: Check if this is triggered by HA restart
      choose:
        - conditions:
            condition: trigger
            id: ha_start
          sequence:
            - delay:
                minutes: 1

    - choose:
        - alias: Turn the fan off if nobody is home
          conditions:
            - condition: state
              entity_id: binary_sensor.anybody_home
              state: "off" # nobody is home
          sequence:
            - service: fan.turn_off
              target:
                entity_id: fan.mech_vent_fan

        - alias: Set fan to High when someone is showering, but only when we are not sleeping.
          conditions:
            - condition: state
              entity_id: binary_sensor.bathroom_hygrostat
              state: "on" # high humidity detected
            - condition: not
              conditions:
                - condition: state
                  entity_id: input_select.house
                  state: "Sleep mode"
          sequence:
            - service: fan.turn_on
              target:
                entity_id: fan.mech_vent_fan
              data:
                percentage: 80 # %

        - alias: Set fan to medium when we are asleep. Everybody is breathing in their beds.
          conditions:
            - condition: state
              entity_id: input_select.house
              state: "Sleep mode"
              for: "00:30:00"
          sequence:
            - service: fan.turn_on
              target:
                entity_id: fan.mech_vent_fan
              data:
                percentage: 45 # %

      alias: Set fan to low during the day
      default:
        - service: fan.turn_on
          target:
            entity_id: fan.mech_vent_fan
          data:
            percentage: 25 # %
